image:
  file: .gitpod.Dockerfile

tasks:
  # - init: gh auth login
  # - init: ln -s /workspace/Android-Studio-Gitpod/AndroidStudio4.1-Configuration ~/.config/Google/AndroidStudio4.1
  # - init: ln -s /workspace/Android-Studio-Gitpod/AndroidStudio4.1-Plugins ~/.local/share/Google/AndroidStudio4.1
  # - command: cd /usr/local/android-studio/bin/ && ./studio.sh
  - prebuild: ./gradlew build
  - command: zsh

github:
  prebuilds:
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

vscode:
  extensions:
    - codezombiech.gitignore@0.6.0:oJP0UqwrXt2Qgt5QRm1BIQ==
    - maddog986.autodocblocker@1.0.2:ey8TGFw83C4aegTkW13AGA==
    - guillaumeisabelle.gixdeko-comments@1.0.115:9iBdt1vwBj1/tP0ccsdtvw==
    - owenfarrell.vscode-microtask@1.0.3:HKM415Hmq45XFIL1HeIdbQ==
    - naturalclar.workspace-settings-json@0.0.10:dO7CSbCBQvxSAZIgNH/jUQ==
    - mathiasfrohlich.kotlin@1.7.1:2Uw0hH38NcpgInldjuwF3g==
