trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  repositoryName: Account-Ledger-Android-Client

steps:
  - checkout: self
    submodules: recursive

  - task: Cache@2.198.0
    inputs:
      key: 'gradleUserHome | "$(Agent.OS)"'
      restoreKeys: gradleUserHome
      path: $(GRADLE_USER_HOME)
    displayName: Gradle User Home Cache

  - task: JavaToolInstaller@0.209.0
    inputs:
      versionSpec: "17"
      jdkArchitectureOption: "x64"
      jdkSourceOption: "PreInstalled"

  - task: Gradle@3.208.0
    displayName: "Gradle assembleDevelopmentDebug : Android APK"
    inputs:
      # TODO : Add build scan, upload build scan results
      gradleOptions: "-Xmx3072m"
      tasks: "assembleDevelopmentDebug"

  - script: "gradlew --stop"
    displayName: Stop Gradle Daemon

  - publish: app/build/outputs/apk/development/debug/app-development-debug.apk
    artifact: $(repositoryName) Debug Apk
