trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  repositoryName: Account-Ledger-Android-Client

steps:
  - checkout: self
    submodules: recursive

  - task: Cache@2.198.0
    inputs:
      key: 'gradleUserHome | "$(Agent.OS)"'
      restoreKeys: gradleUserHome
      path: $(GRADLE_USER_HOME)
    displayName: Gradle User Home Cache

  - task: JavaToolInstaller@0.209.0
    inputs:
      versionSpec: "17"
      jdkArchitectureOption: "x64"
      jdkSourceOption: "PreInstalled"

  - script: |
      sed -i "s|SERVER_ENDPOINT_URL|$SERVER_ENDPOINT_URL|" app/src/main/java/ndk/personal/account_ledger/constants/ServerEndpoint.java
    env:
      SERVER_ENDPOINT_URL: $(SERVER_ENDPOINT_URL)
    displayName: "Update ServerEndpoint constants"

  - task: Gradle@3.208.0
    displayName: "Gradle assembleProductionRelease : Android APK"
    inputs:
      # TODO : Add build scan, upload build scan results
      gradleOptions: "-Xmx3072m"
      tasks: "assembleProductionRelease"

  - publish: app/build/outputs/apk/production/release/app-production-release.apk
    artifact: $(repositoryName) Release Apk

  - script: "./gradlew --stop"
    displayName: Stop Gradle Daemon
